### ISSUE TITLE
Files stuck on processing

### ISSUE THREAD

**Issue by kokaishere** [ImTheSquid/SplitLargeFiles#12]
![image](https://user-images.githubusercontent.com/111226477/184533191-4d8e3b13-9065-44af-9de7-1e2f3ccf9164.png)

None of the files are uploading and the funny part is that the plugin was working 1-2 weeks earlier, but now it doesn't wanna start uploading any of them. I've tried this with multiple types of files with various sizes but no positive result.

I.E.: It says this after uploading the file (35mb):
![image](https://user-images.githubusercontent.com/111226477/184534056-1f70c3fc-a540-4a50-bf61-ddadc12fe111.png)

And now it's stuck here (see the timestamp)

![image](https://user-images.githubusercontent.com/111226477/184534149-aca6ed6d-91b5-437d-9029-17cdeac0b0ad.png)

Restarted it:

![image](https://user-images.githubusercontent.com/111226477/184534916-f0509f50-6bb6-4cba-b1fd-91e84cc1abb0.png)

This is the BD version I'm running:
![image](https://user-images.githubusercontent.com/111226477/184533272-4a98b639-41cd-4d85-a78d-5c17efe91f72.png)

Do you have any workaround for this or is there a patch coming?
Thanks a bunch!

**Comment by kokaishere** [comment]
![image](https://user-images.githubusercontent.com/111226477/184533249-8b7ad07b-e0a5-4438-a7c0-27965e2564be.png)
Windows 11

**Comment by ImTheSquid** [comment]
Bug confirmed (along with some other stuff), I'll look into this.

**Comment by kokaishere** [comment]
> Bug confirmed (along with some other stuff), I'll look into this.

Is there an ETA you have in mind for this? Thanks for replying?

**Comment by ImTheSquid** [comment]
I've been very busy lately so I can't guarantee a time, hopefully it should be fixed in a day or two.
