### ISSUE TITLE
how it works?

### ISSUE THREAD

**Issue by Ga6cha** [ImTheSquid/SplitLargeFiles#14]
Sorry, maybe I’m doing something wrong or I don’t understand how this plugin works, but I throw a file to my friend, it is split into 2 or more and they are combined into 1, and my friend still has several of them, how can he combine them and
 eventually download the file (sorry if the text is strange, I used google translator)

**Comment by ImTheSquid** [comment]
He either needs to have SplitLargeFiles installed on his client as well or he has to use [my site](https://imthesquid.github.io) (specifically the DLFC converter) after downloading all of the individual parts.
