### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by mcpeadventure09** [ImTheSquid/SplitLargeFiles#15]
When i try to send the chunk files discord just says upload failed

![image](https://user-images.githubusercontent.com/69580846/185760252-6bd17bba-b540-4f8b-9235-e6566fe77e18.png)

**Comment by ImTheSquid** [comment]
Update Discord.

**Comment by mcpeadventure09** [comment]
> Update Discord.

na i have it updated i think its cuz discord cant upload more than 10 files at the same time
