### ISSUE TITLE
Softlocks discord after sending any file.

### ISSUE THREAD

**Issue by Fr4Ckt3r** [ImTheSquid/SplitLargeFiles#16]
![javaw_B1BvIDrKj7](https://user-images.githubusercontent.com/50457706/186938671-5f187ed2-4f8b-4546-8630-b6c6081d9368.png)
after clicking reload, it throws an error again.

**Comment by ImTheSquid** [comment]
I don't have any issues. Make sure both the plugin and Discord is fully-updated. If it still doesn't work, tell me all of your version info as well as the size of the file you were trying to upload.
