### ISSUE TITLE
Not working for me (need help)

### ISSUE THREAD

**Issue by dotcf** [ImTheSquid/SplitLargeFiles#2]
Hello,

I have BD with 1.3.0 (latest to download on Homepage) i installed you plugin 2 times by your readme but is it not working. I installed all needed libarys and activated them. I dropp a file into discord that is 50mb big. Its Uploads but not in chunk as you readme picture and after that it says the file is to big. What is wrong, that the script is not working? I already Restarted discord more tomes but no affect. Please help.

**Comment by jaro-git** [comment]
Okay uploading works now but the visual is not shown right..

**Comment by ImTheSquid** [comment]
The latest Discord update broke my plugin, I'll push an emergency patch tonight with the most important fixes then I'll fix other smaller stuff (like context menus) in later updates once the dust settles.

**Comment by jaro-git** [comment]
Okay nice. So you want to fix that so i can upload splited files aigan with right visual show? Thanks for you work.

**Comment by ImTheSquid** [comment]
I just pushed a patch that should fix display and download issues. I'll close this issue once context menus are also back to working.
