### ISSUE TITLE
Uploading a file bigger than 8mb is always showing nitro popup. unuseless.

### ISSUE THREAD

**Issue by dotxyzcf** [ImTheSquid/SplitLargeFiles#21]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/92203938/193902848-6a14bcaf-310a-48fc-bfc3-5ef8c1ce2598.png">

**Comment by dotxyzcf** [comment]
already tried many files

**Comment by ImTheSquid** [comment]
Discord recently released a massive update that completely broke all BetterDiscord plugins, mine included. At the current moment there is no good way to fix them without hacks workarounds, so I'm taking a small break. Once BD releases a way to patch functions again I'll fix the plugin.

**Comment by dotxyzcf** [comment]
Better discord realeased v1.8.0! @ImTheSquid and fixed api etc.

**Comment by dotxyzcf** [comment]
so you maybe need to update bcs the plugin dont work as i said in the first message.

**Comment by ImTheSquid** [comment]
I will fix them as soon as I can, but I am a very busy college student so it will **not** happen until at least this weekend.

**Comment by Bubiko** [comment]
> 

tnx for trying to fix it :) and good luck with your college

**Comment by ImTheSquid** [comment]
Fixed
