### ISSUE TITLE
CompileError

### ISSUE THREAD

**Issue by MightyNumberNine** [ImTheSquid/SplitLargeFiles#4]
the plugin doesn't work ( bd with discord canary, i also tried installing bd on the stable version of discord, but the plugin still doesn't work)

SplitLargeFiles.plugin.js: compileError
    at Object.loadAddon (<anonymous>:4:268126)
    at Object.loadAddon (<anonymous>:4:305956)
    at FSWatcher.<anonymous> (<anonymous>:4:266254)

How can i fix this?

**Comment by MightyNumberNine** [comment]
I'm new to this bd plug-ins and stuff and coding in general, anyways all I did was grabbing the SplitLargeFiles.plugin.js (updated last month) and I putted it in the plug-ins folder, do I need to run cmd or something else to correctly install the plugin?

**Comment by MightyNumberNine** [comment]
[PluginManager] Could not load SplitLargeFiles.plugin.js:

 MetaError: metaNotFound
    at Object.extractMeta (<anonymous>:4:266745)
    at Object..js (<anonymous>:4:267614)
    at Function.o._load (<anonymous>:4:370475)
    at Object.loadAddon (<anonymous>:4:268008)
    at Object.loadAddon (<anonymous>:4:305956)
    at FSWatcher.<anonymous> (<anonymous>:4:266254)

When i put the plugin in the folder this happens, the plugin itself doesn't show in the plugins selection as well, so i cant turn it off or on , it just doesn't load

**Comment by ImTheSquid** [comment]
It seems that your file is somehow corrupt. Try redownloading the file by going [here](https://raw.githubusercontent.com/ImTheSquid/SplitLargeFiles/master/SplitLargeFiles.plugin.js) and using Ctrl+S.

**Comment by MightyNumberNine** [comment]
Okey it worked now, thank you sir!

**Comment by tmccartney2023** [comment]
@ImTheSquid I'm encountering the same problem, but as soon as I've clicked "Console", my whole Discord crashed and I had to log in on my account again. Do you know any fixes for this?
