### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by P13Gabriel** [ImTheSquid/SplitLargeFiles#6]
When I put the SplitLargeFiles.plugin.js in the plugin folder, it says that it's not working.
![Screenshot 2022-04-23 171237](https://user-images.githubusercontent.com/89360742/164909721-58c0c74f-f8f7-49c9-bef4-ba8e71672c41.png)

**Comment by ImTheSquid** [comment]
Can you open the console and screenshot any messages prefixed with `[SplitLargeFiles]`?

**Comment by P13Gabriel** [comment]
I can't open the console from the betterdiscord because the plugin it's not in the plugins section and it is in the folder

**Comment by P13Gabriel** [comment]
Nvm, I fixed it, I downloaded it again from another issues closed.
Thank you
