### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jowilksasella** [ImTheSquid/SplitLargeFiles#8]
I drag SplitLargeFiles.plugin.js into the plugin folder and when I upload a 49MB video it pops up with this error.
![mFlGKl0 - Imgur](https://user-images.githubusercontent.com/81877402/170520503-cdbed3c9-3ef9-4ec5-b69e-82195e863f9d.png)

**Comment by jowilksasella** [comment]
And I uploaded a different video which is 46MB and it still not working. Pops up the same error.

**Comment by ImTheSquid** [comment]
Make sure the plugin is enabled then try again. If there's still an error, open the console (Settings->BD Settings->Dev Settings->Enable Dev Tools, then Ctrl+Shift+I), upload a file again and send a screenshot of the error. The current version of the plugin works fine for me with a file upload size of 47MB.

**Comment by jowilksasella** [comment]
![image](https://user-images.githubusercontent.com/81877402/170743129-8baded7e-9424-4bdf-af30-3f67474a6190.png)
Like this?

**Comment by ImTheSquid** [comment]
Click on the Console tab in the top right instead of Elements.

**Comment by jowilksasella** [comment]
![image](https://user-images.githubusercontent.com/81877402/170743485-8e38d2fc-7dee-4829-ab1f-7deea3a0ea90.png)

**Comment by ImTheSquid** [comment]
There doesn't seem to be anything wrong. Try redownloading the plugin and send a screenshot of both when you first enable it and when you try to upload a file.

**Comment by jowilksasella** [comment]
Thank you so much! It works now, I guess because of conflicts with other libraries.
