### ISSUE TITLE
need a progress bar for download files

### ISSUE THREAD

**Issue by hiroshil** [ImTheSquid/SplitLargeFiles#9]
and how to share direct link to download large files?

**Comment by ImTheSquid** [comment]
Added the download readout with [4db244919cfc89e4ee6b8fa7800a49f0ff6876d6](https://github.com/ImTheSquid/SplitLargeFiles/commit/4db244919cfc89e4ee6b8fa7800a49f0ff6876d6). For sharing, just download and upload the file again for right now.

**Comment by hiroshil** [comment]
how about speed download, pause and cancel, bro

**Comment by ImTheSquid** [comment]
Sorry, I'm not writing a full download manager for a while. If someone else wants to do it and open a pull request they can.
